services:
  - type: web
    name: github-api-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /health
